version: '3.8'

services:
  erpovy-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: erpovy-landing
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.local
