"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, ArrowDown, Check, ChevronDown, LayoutDashboard, Package, Wallet, Users, Factory, ShoppingBag, CircleCheck, Plus } from "lucide-react";
import { PRICING_PLANS } from "@/content/pricingData";
import { FAQ_DATA } from "@/content/faqData";
import s from "./MarketingHome.module.css";
const views = [
    { label: "Genel bakış", icon: LayoutDashboard, title: "İşinizin büyük resmi.", subtitle: "Bugün işletmenizde neler oluyor?", metrics: [["Toplam satış", "₺284.500", "Bu ay"], ["Bekleyen sipariş", "24", "8 sevkiyata hazır"], ["Tahsil edilecek", "₺86.250", "12 açık fatura"]], chart: "Satış performansı", bars: [36, 52, 43, 66, 57, 78, 65, 87, 73, 95, 82, 100] },
    { label: "Satış & CRM", icon: Users, title: "Her fırsatın bir sonraki adımı.", subtitle: "Tekliften siparişe, müşteri ilişkileriniz burada.", metrics: [["Açık teklif", "18", "Değerlendirmede"], ["Onaylanan teklif", "₺124.000", "Bu ay"], ["Aktif müşteri", "64", "Müşteri portföyü"]], chart: "Satış hareketleri", bars: [25, 40, 35, 55, 45, 62, 72, 65, 80, 74, 92, 86] },
    { label: "Stok & Depo", icon: Package, title: "Doğru ürün. Doğru yerde.", subtitle: "Stok durumunuzu ve depo hareketlerini izleyin.", metrics: [["Ürün çeşidi", "1.248", "Kayıtlı ürün"], ["Kritik stok", "8", "Kontrol bekliyor"], ["Hazır sevkiyat", "16", "Depo çıkışı bekliyor"]], chart: "Depo hareketleri", bars: [70, 45, 65, 40, 80, 60, 95, 75, 65, 85, 55, 90] },
    { label: "Finans", icon: Wallet, title: "Rakamlar net. Kararlar güçlü.", subtitle: "Alacak, ödeme ve nakit akışını birlikte görün.", metrics: [["Tahsilat", "₺198.250", "Bu ay"], ["Açık alacak", "₺86.250", "12 açık fatura"], ["Planlı ödeme", "₺42.800", "Bu hafta"]], chart: "Tahsilat görünümü", bars: [30, 45, 38, 60, 50, 75, 60, 85, 72, 95, 83, 100] }
];
const steps = [
    { title: "Teklifinizi hazırlayın.", text: "Müşteriyi, ürünleri ve fiyatı aynı yerde buluşturun. Satış fırsatının hangi aşamada olduğunu görün.", tag: "TEKLİF · TKL-1042", status: "Onaylandı", value: "₺24.000", detail: "100 koli ambalaj · Örnek müşteri", icon: ShoppingBag },
    { title: "Stoktan sevkiyata ilerleyin.", text: "Siparişin ürünlerini ve depo durumunu takip edin. Operasyon ekibiniz bir sonraki adımı net görsün.", tag: "DEPO · ANA DEPO", status: "Sevkiyata hazır", value: "100 koli", detail: "Ambalaj kutusu · A-3 rafı", icon: Package },
    { title: "Tahsilatı gözden kaçırmayın.", text: "Fatura ve cari hesap hareketlerini takip edin. İşin finansal tarafı da aynı hikâyenin parçası olsun.", tag: "FATURA · FTR-1042", status: "Vade takibinde", value: "₺24.000", detail: "Örnek müşteri · 30 gün vade", icon: Wallet }
];
const modules = [
    { icon: Wallet, name: "Finans & muhasebe", text: "Nakit akışı, cari hesaplar ve faturalar. Rakamların arkasındaki resmi görün.", tags: "CARİ HESAP · KASA · BANKA" },
    { icon: Users, name: "Satış & müşteri ilişkileri", text: "İlk görüşmeden siparişe. Her müşterinin ve her fırsatın izini sürün.", tags: "TEKLİF · SATIŞ · CRM" },
    { icon: Package, name: "Stok & operasyon", text: "Depoda ne var, ne yolda? Ürün ve sevkiyat hareketlerini birlikte takip edin.", tags: "STOK · DEPO · LOJİSTİK" },
    { icon: Factory, name: "Üretim & ekip", text: "Planları işe dönüştürün. Üretim emirlerini, projeleri ve görevleri düzenleyin.", tags: "ÜRETİM · PROJE · GÖREV" }
];
export function MarketingHome() {
    const [activeView, setActiveView] = useState(0);
    const [activeStep, setActiveStep] = useState(0);
    const view = views[activeView], step = steps[activeStep], StepIcon = step.icon;
    return <main className={s.home}>
 <section className={s.hero}><div className={s.container}>
 <div className={s.eyebrow}><i /> İŞİNİZİN YENİ ÇALIŞMA DÜZENİ</div>
 <div className={s.heroHeading}><h1>Her şey yerli yerinde.<br /><span>İşiniz bir adım önde.</span></h1><div className={s.heroAside}><p>Satış, stok, finans ve ekibiniz. Erpovy ile işletmenizin tamamını aynı yerden yönetin.</p><a href="#urun" className={s.textLink}>Büyük resmi görün <ArrowDown size={17}/></a></div></div>
 <div className={s.heroActions}><Link href="/demo/" className={s.primary}>İşletmenize özel demo <ArrowUpRight size={20}/></Link><span>20 dakika. Sizin işiniz, sizin senaryonuz.</span></div>
 <div id="urun" className={s.productStage}><div className={s.stageTop}><span><i /> DAHA NET BİR İŞ GÜNÜ</span><span>ERPOVY / ÜRÜN TURU</span></div>
 <div className={s.dashboard}><aside className={s.sidebar}><div className={s.appBrand}>erpovy<sup>®</sup></div><div className={s.workspace}><b>A</b><div>Atlas Ticaret<small>Örnek çalışma alanı</small></div><ChevronDown size={14}/></div><small className={s.sideLabel}>ÇALIŞMA ALANI</small><nav className={s.viewNav} aria-label="Ürün önizleme görünümleri">{views.map((v, i) => <button key={v.label} aria-pressed={i === activeView} onClick={() => setActiveView(i)}><v.icon size={17}/><span>{v.label}</span></button>)}</nav><div className={s.sidebarBottom}><b>AY</b><div>Ayşe Yılmaz<small>Yönetici</small></div></div></aside>
 <div><div className={s.appTop}><span>Çalışma alanı / {view.label}</span><span>Eylül 2026 <ChevronDown size={12}/></span></div><div className={s.appContent}><div className={s.appTitle}><div><h2>{view.title}</h2><p>{view.subtitle}</p></div><span>Örnek veriler</span></div><div className={s.metrics}>{view.metrics.map(([label, value, note]) => <div key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</div>
 <div className={s.dashboardGrid}><div className={s.chart}><div className={s.widgetTitle}>{view.chart}<span>Bu yıl <ChevronDown size={12}/></span></div><div className={s.barChart} role="img" aria-label={`${view.chart}: temsili aylık değerler`}><div className={s.chartLines}><span>300 bin</span><span>200 bin</span><span>100 bin</span></div><div className={s.bars}>{view.bars.map((height, i) => <div key={i} style={{ height: `${height}%` }}><span>{["O", "Ş", "M", "N", "M", "H", "T", "A", "E", "E", "K", "A"][i]}</span></div>)}</div></div></div><div className={s.activity}><div className={s.widgetTitle}>Günün akışı <span>3 işlem</span></div>{[["Sipariş onaylandı", "Atlas Ticaret · #1042", "09:42"], ["Sevkiyat hazırlandı", "Ana depo · 100 koli", "10:15"], ["Tahsilat kaydedildi", "Banka hesabı · ₺12.500", "11:08"]].map(([title, detail, time]) => <div className={s.activityRow} key={title}><CircleCheck size={17}/><div><strong>{title}</strong><small>{detail}</small></div><time>{time}</time></div>)}<div className={s.activityNote}><Check size={14}/> Ekibiniz aynı bilgiyle ilerlesin.</div></div></div></div></div></div>
 <div className={s.stageBottom}><span>Bir görünüm seçin, işinize daha yakından bakın.</span><span>Temsili ürün arayüzü ve örnek veriler <ArrowUpRight size={14}/></span></div></div>
 <div className={s.proofStrip}><p>İşletmenizin her parçası.<br /><strong>Birlikte, daha güçlü.</strong></p>{["Bulut tabanlı erişim", "İhtiyaca göre modüller", "Türkçe arayüz"].map(t => <span key={t}><Check size={17}/>{t}</span>)}</div></div></section>
 <section id="hikaye" className={s.section}><div className={s.container}><div className={s.sectionHead}><div><span className={s.eyebrow}>01 / BİRBİRİNE BAĞLI BİR İŞ AKIŞI</span><h2>Bir sipariş.<br />Baştan sona netlik.</h2></div><p>Birbirinden kopuk dosyalar ve tekrar tekrar sorulan sorular yerine, herkesin takip edebildiği bir iş akışı.</p></div><div className={s.workflowGrid}><div className={s.steps}>{steps.map((item, i) => <button key={item.title} onClick={() => setActiveStep(i)} aria-expanded={activeStep === i} aria-controls="workflow-detail" className={activeStep === i ? s.selectedStep : ""}><span>0{i + 1}</span><div><h3>{item.title}</h3>{activeStep === i && <p>{item.text}</p>}</div><ArrowUpRight size={20}/></button>)}</div><div id="workflow-detail" className={s.orderStage} aria-live="polite"><div className={s.orderCaption}>HER ADIMDA AYNI HİKÂYE <span>0{activeStep + 1} / 03</span></div><div className={s.orderCard}><div className={s.orderIcon}><StepIcon size={26}/><span>{step.status}</span></div><small>{step.tag}</small><strong>{step.value}</strong><p>{step.detail}</p><div className={s.orderFooter}><CircleCheck size={17}/>{step.title}<ArrowUpRight size={15}/></div></div><p className={s.exampleLabel}>Örnek iş akışı · temsili veriler</p></div></div></div></section>
 <section id="moduller" className={`${s.section} ${s.modules}`}><div className={s.container}><div className={s.sectionHead}><div><span className={s.eyebrow}>02 / SİZİN İŞİNİZE GÖRE</span><h2>Bugün ihtiyacınız olan.<br />Yarın büyütebileceğiniz.</h2></div><Link className={s.textLink} href="/moduller/">Tüm modülleri keşfedin <ArrowUpRight size={19}/></Link></div><div className={s.moduleGrid}>{modules.map((item, i) => <Link href="/moduller/" key={item.name} className={s.module}><div className={s.moduleTop}><item.icon size={27} strokeWidth={1.4}/><span>0{i + 1}</span></div><h3>{item.name}</h3><p>{item.text}</p><div className={s.moduleFoot}><small>{item.tags}</small><ArrowUpRight size={20}/></div></Link>)}</div><div id="sektorler" className={s.sectors}><span>Farklı işler. Ortak bir düzen.</span>{["Ticaret", "Üretim", "Hizmet", "E-ticaret"].map(t => <Link key={t} href="/cozumler/">{t}<ArrowUpRight size={15}/></Link>)}</div></div></section>
 <section className={s.section}><div className={s.container}><div className={s.sectionHead}><div><span className={s.eyebrow}>03 / BÜYÜMENİZE ALAN AÇIN</span><h2>İşinizin ölçeğine<br />uygun bir başlangıç.</h2></div><p>Önce ihtiyacınızı anlayalım. Modülleri, kullanıcıları ve geçiş planını birlikte netleştirelim.</p></div><div className={s.priceGrid}>{PRICING_PLANS.map((plan, i) => <div key={plan.id} className={`${s.priceCard} ${i === 1 ? s.featuredPrice : ""}`}><div className={s.priceLabel}>{plan.tagline}{i === 1 && <span>BÜYÜYEN EKİPLER</span>}</div><h3>{plan.name.replace("Erpovy ", "")}</h3><div className={s.price}>{plan.annualPrice}<small>/ yıl</small></div><p>{plan.usersIncluded} kullanıcı dahil</p><div className={s.priceFeatures}>{plan.features.slice(0, 3).map(f => <span key={f}><Check size={16}/>{f}</span>)}</div><Link href="/demo/" className={i === 1 ? s.primary : s.outline}>Birlikte değerlendirelim <ArrowUpRight size={18}/></Link><small className={s.setup}>{plan.setupCost}</small></div>)}</div><div className={s.pricingNote}><span>Kurulum bedelleri yıllık lisansa dahil değildir. Vergi ve nihai kapsam teklif aşamasında netleştirilir.</span><Link href="/fiyatlandirma/">Paketleri karşılaştırın <ArrowRight size={16}/></Link></div></div></section>
 <section id="sss" className={`${s.section} ${s.faq}`}><div className={`${s.container} ${s.faqGrid}`}><div><span className={s.eyebrow}>AKLINIZDAKİ SORULAR</span><h2>Birlikte<br />netleştirelim.</h2><Link href="/iletisim/" className={s.textLink}>Bizimle konuşun <ArrowUpRight size={18}/></Link></div><div>{FAQ_DATA.filter((_, i) => [0, 1, 2, 4, 6].includes(i)).map(item => <details key={item.id}><summary>{item.question}<Plus size={20}/></summary><p>{item.answer}</p></details>)}</div></div></section>
 <section className={s.closing}><div className={s.container}><div className={s.eyebrow}>BİR SONRAKİ ADIM, DAHA NET BİR İŞ GÜNÜ.</div><div className={s.closingGrid}><h2>İşinizin potansiyelini<br /><span>birlikte açığa çıkaralım.</span></h2><div><p>20 dakikayı ayırın.<br />Erpovy’yi kendi işiniz üzerinden keşfedin.</p><Link href="/demo/" className={s.primary}>Size özel demoyu planlayalım <ArrowUpRight size={20}/></Link></div></div><div className={s.closingBottom}><span>İŞİNİZİN TAMAMINA HÂKİM OLUN.</span><span>erpovy®</span></div></div></section>
 </main>;
}
