import type { Metadata } from "next";
import { InnerPage } from "@/components/InnerPage";
import s from "@/components/InnerPages.module.css";
export const metadata: Metadata = {
    title: "Hakkımızda & Misyonumuz | Erpovy Yeni Nesil Bulut ERP",
    description: "Erpovy'nin kuruluş hikayesi, misyonu ve vizyonu. İşletmeleri hantal masaüstü programlarından kurtararak modern bulut hızında dijitalleştiriyoruz.",
    alternates: {
        canonical: "https://www.erpovy.com/hakkimizda",
    },
};
export default function Page() {
    return (<InnerPage label="Hakkımızda" title="İyi yönetilen işler." accent="Birlikte büyüyen ekipler." description="Erpovy, işletmenizin farklı parçalarını ortak bir çalışma düzeninde buluşturmak için var. Daha anlaşılır süreçler ve daha net kararlar için."><section className={s.content}><div className={s.container}><div className={s.story}><div><span className={s.eyebrow}>NEDEN ERPOVY?</span><h2>İşinize odaklanmak için<br />yer açıyoruz.</h2><p>Bir sipariş satış ekibinde başlar; depoya, sevkiyata ve finansa uzanır. Bilgi farklı dosya ve sistemlerde kaldığında, ekipler aynı sorulara tekrar tekrar yanıt arar.</p><p>Erpovy’yi bu parçaları bir araya getiren modüler bir iş yönetimi platformu olarak tasarlıyoruz. Amacımız, işletmenizin günlük akışını görünür kılmak ve ekiplerin aynı bilgiyle ilerlemesini sağlamak.</p><p>Önce ihtiyacınızı anlamaya, sonra ona uygun bir kapsam oluşturmaya inanıyoruz. Çünkü doğru yazılım, işinizin çalışma biçimine uyum sağlamalı.</p></div><div className={s.manifesto}><span>BAKIŞ AÇIMIZ</span><h2>Daha çok ekran değil.<br />Daha net bir<br />çalışma düzeni.</h2><p>Satıştan üretime, stoktan finansa.<br />İşletmenizin tamamını birlikte düşünün.</p></div></div><div className={s.sectionHead}><div><span className={s.eyebrow}>ÇALIŞMA İLKELERİMİZ</span><h2>Ürünün arkasındaki yaklaşım.</h2></div></div><div className={s.valueGrid}>{[{ title: "İhtiyaca göre kapsam", text: "Modülleri işletmenizin önceliklerine göre belirler, büyüme yolculuğunuzu birlikte planlarız." }, { title: "Ortak bilgi", text: "Ekiplerin aynı kayıtlar ve süreçler üzerinden çalışmasını önemseriz." }, { title: "Anlaşılır deneyim", text: "Günlük işleri takip etmeyi kolaylaştıran, Türkçe ve tutarlı bir arayüz hedefleriz." }, { title: "Bulut üzerinden erişim", text: "İşletmenizin çalışma alanına tarayıcı üzerinden erişebilmesini sağlarız." }, { title: "Net bir başlangıç", text: "Lisans, kurulum ve veri aktarımı kapsamını işe başlamadan önce birlikte netleştiririz." }, { title: "Doğrudan iletişim", text: "Sorularınızı dinler, ürün görüşmesini sizin gerçek iş süreçlerinize odaklarız." }].map((item, i) => <article key={item.title}><span>0{i + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section></InnerPage>);
}
